//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moments.Data.MySqlDataSource.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class photo1
    {
        public photo1()
        {
            this.photopersonmappings = new HashSet<photopersonmapping>();
        }
    
        public int photoId { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    
        public virtual ICollection<photopersonmapping> photopersonmappings { get; set; }
    }
}
