//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moments.Data.MySqlDataSource.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class phototag
    {
        public int tagId { get; set; }
        public Nullable<int> photoId { get; set; }
        public Nullable<int> personId { get; set; }
    
        public virtual person person { get; set; }
        public virtual photo photo { get; set; }
    }
}
