//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moments.Data.MySqlDataSource.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.photos = new HashSet<photo>();
            this.friends = new HashSet<friend>();
        }
    
        public int userid { get; set; }
        public Nullable<int> peopleId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedBy { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string emailId { get; set; }
        public string gender { get; set; }
        public Nullable<int> userIdentifier { get; set; }
    
        public virtual person person { get; set; }
        public virtual ICollection<photo> photos { get; set; }
        public virtual ICollection<friend> friends { get; set; }
    }
}
